# Generated by Django 5.1.6 on 2025-02-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.AddField(
            model_name='customuser',
            name='button_click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
