# Generated by Django 5.1.6 on 2025-02-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_customuser_age_customuser_button_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dobre',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zle',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
