# Generated by Django 5.1.6 on 2025-03-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_customuser_dobre_customuser_zle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stosunek',
            field=models.IntegerField(default=0),
        ),
    ]
