# Generated by Django 5.1.6 on 2025-03-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_customuser_stosunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stosunek',
            field=models.IntegerField(default=0),
        ),
    ]
